### ISSUE TITLE
run-war not working with grails 2.2.4 and elasticsearch 0.0.4.6

### ISSUE THREAD

**Issue by chrisupb** [noamt/elasticsearch-grails-plugin#134]
My Grails version is: 2.2.4

My projects BuildConfig contains grails.project.dependency.resolution.plugins = { runtime ":elasticsearch:0.0.4.6" }

When deploying my WAR to the embedded jetty everything works. With a Tomcat 7.0.42 the following error occures:

2015-11-11 16:01:30,303 [localhost-startStop-2] ERROR StackTrace  - Full Stack Trace:
org.springframework.beans.factory.BeanCreationException: Error creating bean with name     'pluginManager' defined in ServletContext resource [/WEB-INF/applicationContext.xml]: Invocation of init method failed; nested exception is groovy.lang.MissingMethodException: No signature of method: java.util.ArrayList.sort() is applicable for argument types: (org.codehaus.groovy.grails.plugins.VersionComparator) values: [org.codehaus.groovy.grails.plugins.VersionComparator@2feda493]
Possible solutions: sort(), sort(groovy.lang.Closure), sort(boolean), sort(boolean, java.util.Comparator), sort(boolean, groovy.lang.Closure), wait()
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1455)

*Caused by:* groovy.lang.MissingMethodException: No signature of method: java.util.ArrayList.sort() is applicable for argument types: (org.codehaus.groovy.grails.plugins.VersionComparator) values: [org.codehaus.groovy.grails.plugins.VersionComparator@2feda493]
Possible solutions: sort(), sort(groovy.lang.Closure), sort(boolean), sort(boolean, java.util.Comparator), sort(boolean, groovy.lang.Closure), wait()
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:56)

**Comment by chrisupb** [comment]
OK I just realized that it is not a webapplication container issue. It's the problen with _run-war_ or packaging a WAR in general.

I created a fresh Grails 2.2.4 project and only added :elasticsearch:0.0.4.6" => this causes the same error as above.

**Comment by chrisupb** [comment]
Solution:
Use at least grails 2.3.1 and
 runtime ":elasticsearch:0.0.4.6", {
            exclude "org.codehaus.groovy:groovy-all"
        }
