### ISSUE TITLE
Support for Elasticsearch 2.x

### ISSUE THREAD

**Issue by dalibor-frivaldsky** [noamt/elasticsearch-grails-plugin#135]
Elasticsearch 2.x has been out and stable for some time. Are there any plans to add support for it?

**Comment by donbeave** [comment]
Hi @dalibor-frivaldsky 

I preparing to update this fork (https://github.com/donbeave/grails-elasticsearch/tree/grails3) to support 2.x version.

**Comment by SAgrawal14** [comment]
:+1:

**Comment by priyanshuch** [comment]
:+1:

**Comment by dalibor-frivaldsky** [comment]
Hi @donbeave 

that is great! Do you have any estimate for the availability of 2.x support? Thanks!

**Comment by johngamarra** [comment]
@donbeave please can you tell us if you are going to do a release of your fork? thanks!

**Comment by PhilipWu** [comment]
For those that are interested,
I've created a branch in my own repository starting from version 0.4.3 as the baseline and modified it to work with **Grails 2.x** and **ElasticSearch 2.1.0**. This is good for those that are not quite ready to switch to grails 3.x

also in my version, I've updated the API to support aggregation queries

I've done some basic testing importing records and searching and so far it seems to work.

The repo is here:

https://bitbucket.org/australianphenomicsfacility/elasticsearch-grails-plugin-apf/branch/elasticsearch-plugin-2.1.0

Cheers

**Comment by marcoscarceles** [comment]
Sorry @PhilipWu I hadn't realised there was already traction for a ES 2.x Grails 2.x version... I've just submitted PR #143 which I believe satisfies what's requested here. Feel free to have a look and comment.
@noamt Would there be possible to get permissions to release on the grails site? Also... what do you think about #141 ?

**Comment by PhilipWu** [comment]
Thanks **marcoscarceles**
I'm glad to see these changes becoming official.  
although I'm using my own branch, most of the changes you've made look the same, and I can confirm we've been running for several weeks in production environment without issues  for both searching and indexing operations.

cheers

**Comment by marcoscarceles** [comment]
@PhilipWu :+1:

**Comment by jadelus** [comment]
@PhilipWu which version of Grails have you tested this with? I am trying to run with 2.5.4 and having some issues. Thanks.

**Comment by PhilipWu** [comment]
@jadelus

the grails version i use is 2.4.4

what kinds of problems are you having? and which plugin are you using?

good luck

On Sun, Apr 10, 2016 at 8:54 AM, jadelus <notifications@github.com> wrote:

> @PhilipWu <https://github.com/PhilipWu> which version of Grails have you
> tested this with? I am trying to run with 2.5.4 and having some issues.
> Thanks.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/noamt/elasticsearch-grails-plugin/issues/135#issuecomment-207867545>
>



-- 
/**
* Philip Wu
*/

**Comment by jadelus** [comment]
@PhilipWu I am using elasticsearch:0.0.4.6. It worked fine in run-app but I'm getting the following error when trying to run a standalone jar or war file:

`java.lang.ExceptionInInitializerError
	at org.codehaus.groovy.runtime.InvokerHelper.<clinit>(InvokerHelper.java:62)
	at groovy.lang.GroovyObjectSupport.<init>(GroovyObjectSupport.java:32)
	at org.codehaus.groovy.grails.commons.AbstractGrailsApplication.<init>(AbstractGrailsApplication.java:45)
	at org.codehaus.groovy.grails.commons.DefaultGrailsApplication.<init>(DefaultGrailsApplication.java:95)
	at org.codehaus.groovy.grails.commons.DefaultGrailsApplication.<init>(DefaultGrailsApplication.java:91)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at java.lang.Class.newInstance(Class.java:379)
	at org.codehaus.groovy.grails.plugins.log4j.web.util.Log4jConfigListener.createGrailsApplication(Log4jConfigListener.java:54)
	at org.codehaus.groovy.grails.plugins.log4j.web.util.Log4jConfigListener.contextInitialized(Log4jConfigListener.java:42)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4772)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5196)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1409)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1399)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: groovy.lang.GroovyRuntimeException: Conflicting module versions. Module [groovy-all is loaded in version 2.4.3 and you are trying to load version 2.4.4
	at org.codehaus.groovy.runtime.metaclass.MetaClassRegistryImpl$DefaultModuleListener.onModule(MetaClassRegistryImpl.java:509)
	at org.codehaus.groovy.runtime.m12n.ExtensionModuleScanner.scanExtensionModuleFromProperties(ExtensionModuleScanner.java:77)
	at org.codehaus.groovy.runtime.m12n.ExtensionModuleScanner.scanExtensionModuleFromMetaInf(ExtensionModuleScanner.java:71)
	at org.codehaus.groovy.runtime.m12n.ExtensionModuleScanner.scanClasspathModules(ExtensionModuleScanner.java:53)
	at org.codehaus.groovy.runtime.metaclass.MetaClassRegistryImpl.<init>(MetaClassRegistryImpl.java:110)
	at org.codehaus.groovy.runtime.metaclass.MetaClassRegistryImpl.<init>(MetaClassRegistryImpl.java:71)
	at groovy.lang.GroovySystem.<clinit>(GroovySystem.java:33)
	... 21 more
`

`groovy-all is loaded in version 2.4.3 and you are trying to load version 2.4.4` implies it's an issue with the version of groovy - Grails 2.5.4 uses groovy 2.4.4 and I guess elasticsearch 0.0.4.6 uses 2.4.3?

Thanks for your help

**Comment by marcoscarceles** [comment]
ES 2.1.x support for Grails 2.x apps is coming up on release 0.1.0 (357d171)

@noamt @puneetbehl any idea when could this be released? Cheers!

**Comment by PhilipWu** [comment]
@jadelus

The ES plugin i'm using is one that I customized myself by modifying the
source code, so we're using very different versions.
As Marcos said, there's a pending release that you'll want to hold out for
before upgrading your elasticsearch.

Good luck

On Mon, Apr 11, 2016 at 4:18 PM, Marcos Carceles <notifications@github.com>
wrote:

> ES 2.1.x support for Grails 2.x apps is coming up on release 0.1.0 (
> 357d171
> <https://github.com/noamt/elasticsearch-grails-plugin/commit/357d171cd773d24bba1d8a697762ae5220a03402>
> )
>
> @noamt <https://github.com/noamt> @puneetbehl
> <https://github.com/puneetbehl> any idea when could this be released?
> Cheers!
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/noamt/elasticsearch-grails-plugin/issues/135#issuecomment-208180950>
>



-- 
/**
* Philip Wu
*/

**Comment by jadelus** [comment]
@marcoscarceles thanks for the pointer. Unfortunately it looks like the new version only goes from Grails 2.4.4 to 2.4.5 which bumps the groovy version from 2.3.7 to 2.3.11. That will probably still have the same issue with Groovy 2.4.4. Perhaps I can take a look at what you did @PhilipWu and move it up to the latest 2.5 Grails release.

Thanks

**Comment by puneetbehl** [comment]
@marcoscarceles version 0.1.0 is published.
