### ISSUE TITLE
Can't get grails-2.x branch to work

### ISSUE THREAD

**Issue by ArtemZ** [noamt/elasticsearch-grails-plugin#149]
Hello,

I'm trying to use elasticsearch plugin (branch grails-2.x) with my grails 2.4.5 application, but application fails at start with the following exception:

> context.GrailsContextLoaderListener Error initializing Grails: Error creating bean with name 'elasticSearchBootStrapHelper': Cannot resolve reference to bean 'elasticSearchService' while setting bean property 'elasticSearchService'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'elasticSearchService': Initialization of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'domainInstancesRebuilder': Cannot resolve reference to bean 'elasticSearchClient' while setting bean property 'elasticSearchClient'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'elasticSearchClient': FactoryBean threw exception on object creation; nested exception is java.lang.IllegalStateException: path.home is not configured
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'elasticSearchBootStrapHelper': Cannot resolve reference to bean 'elasticSearchService' while setting bean property 'elasticSearchService'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'elasticSearchService': Initialization of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'domainInstancesRebuilder': Cannot resolve reference to bean 'elasticSearchClient' while setting bean property 'elasticSearchClient'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'elasticSearchClient': FactoryBean threw exception on object creation; nested exception is java.lang.IllegalStateException: path.home is not configured
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.invoke(DefaultMBeanServerInterceptor.java:819)
	at com.sun.jmx.mbeanserver.JmxMBeanServer.invoke(JmxMBeanServer.java:801)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'elasticSearchService': Initialization of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'domainInstancesRebuilder': Cannot resolve reference to bean 'elasticSearchClient' while setting bean property 'elasticSearchClient'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'elasticSearchClient': FactoryBean threw exception on object creation; nested exception is java.lang.IllegalStateException: path.home is not configured
	... 5 more
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'domainInstancesRebuilder': Cannot resolve reference to bean 'elasticSearchClient' while setting bean property 'elasticSearchClient'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'elasticSearchClient': FactoryBean threw exception on object creation; nested exception is java.lang.IllegalStateException: path.home is not configured
	... 5 more
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'elasticSearchClient': FactoryBean threw exception on object creation; nested exception is java.lang.IllegalStateException: path.home is not configured
	... 5 more
Caused by: java.lang.IllegalStateException: path.home is not configured
	at org.elasticsearch.env.Environment.<init>(Environment.java:99)
	at org.elasticsearch.node.internal.InternalSettingsPreparer.prepareEnvironment(InternalSettingsPreparer.java:81)
	at org.elasticsearch.node.Node.<init>(Node.java:128)
	at org.elasticsearch.node.NodeBuilder.build(NodeBuilder.java:145)
	at org.elasticsearch.node.NodeBuilder.node(NodeBuilder.java:152)
	at org.grails.plugins.elasticsearch.ClientNodeFactoryBean.getObject(ClientNodeFactoryBean.groovy:201)
	... 5 more

The plugin configuration is default except for these properties:
> elasticSearch.client.mode = 'local'
> elasticSearch.datastoreImpl = "hibernateDatastore"
> elasticSearch.index.store.type = 'memory'

Any ideas what can be wrong?

**Comment by puneetbehl** [comment]
@ArtemZ please add sample github application. Also, seems like `java.lang.IllegalStateException: path.home is not configured`

**Comment by puneetbehl** [comment]
@ArtemZ  please try with memory type `simplefs`. Following are the update properties:
```
elasticSearch.client.mode = 'local'
elasticSearch.datastoreImpl = 'hibernateDatastore`
elasticSearch.index.store.type = 'simplefs`
```

**Comment by younisalrawi** [comment]
I am still having this problem with 2.5 using mode of 'node'

Is there any update on this ?

**Comment by biohazardxxx** [comment]
I have the same issue with Grails 2.5.4

ES config:
elasticSearch.datastoreImpl = 'hibernateDatastore'
elasticSearch.client.mode = 'local'
elasticSearch.index.store.type = 'simplefs'
elasticSearch.path.data="C:/temp/toolDevTemp/"

included via:
compile "org.grails.plugins:elasticsearch:0.1.0"

**Comment by puneetbehl** [comment]
I am at the GR8Conf US these days :) and  might  not be able to look into this in next 2-3 days. But, could you please create a sample application meanwhile which replicates the issue. 

Thanks

**Comment by biohazardxxx** [comment]
while preparing the example app I could not recreate this.
as workaround adding the ES home via the Tomcat JAVA_OPTS: -Des.path.home=C:\elasticsearch-2.3.4\
works.
I compared from the example  to my failing project the following files and removed all major differences:

- Config.groovy
- Build.groovy
- Application.properties
- DataSource.groovy
But issue remains. Any idea where to look else?

BTW: there seems to be a dependency to jline:jline:2.14.2 when deploying as war.

**Comment by puneetbehl** [comment]
One might see this exception if configured `elasticSearch.client.mode=node` or `dataNode`. So, we need to define `es.path.home` in VM options as mentioned by @biohazardxxx  

For Grails application to run simply run as `grails run-app -Des.path.home=<PATH_TO_ELASTICSEARCH_HOME_DIR>`.

**Comment by rpalcolea** [comment]
Hi @puneetbehl 

how can I set the `path.home` using Grails 3? I tried with `grails -Des.path.home=myPath run-app` but didn’t work. I got the classic:

```elasticSearchClient': FactoryBean threw exception on object creation; nested exception is java.lang.IllegalStateException: path.home is not configured```

Any suggestion for production env?

Thanks

**Comment by rpalcolea** [comment]
Oh never mind, found the way to do it:

```
bootRun {
    jvmArgs = ['-Des.path.home=/Users/rperez/elasticsearch-2.3']
}
```

in `build.gradle`

**Comment by bioform** [comment]
@puneetbehl , I guess you need to reopen this issue. 
this issue is reproducable for "node" client mode. From documentation for elasticsearch-grails-plugin:
> The plugin create its own node and join the ElasticSearch cluster as a client node (node.client = true). This setting requires that you have an ElasticSearch instance running and available on your network (use the discovery feature)

The main thing is *"ElasticSearch instance running and available on your network"*, but you suggested to provide path to a local instance(not a network) on elasticsearch

So this issue is critical since "node" client mode is default for production environment
