### ISSUE TITLE
Error on Grails V2.5.0 with Elasticsearch plugin V0.1.0

### ISSUE THREAD

**Issue by yang22zhang** [noamt/elasticsearch-grails-plugin#159]
I'm having an error when using  Grails V2.5.0 with Elasticsearch plugin V0.1.0.
This problem does not appear in the Elasticsearch plugin V0.0.4.6.
```
ERROR org.codehaus.groovy.grails.web.context.GrailsContextLoaderListener Error initializing the application: Error creating bean with name 'searchableClassMappingConfigurator': Invocation of init method failed; nested exception is java.lang.IllegalArgumentException: Mapper for [applicableSeries] conflicts with existing mapping in other types[object mapping [applicableSeries] can't be changed from nested to non-nested]
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'searchableClassMappingConfigurator': Invocation of init method failed; nested exception is java.lang.IllegalArgumentException: Mapper for [applicableSeries] conflicts with existing mapping in other types[object mapping [applicableSeries] can't be changed from nested to non-nested]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: Mapper for [applicableSeries] conflicts with existing mapping in other types[object mapping [applicableSeries] can't be changed from nested to non-nested]
        at org.elasticsearch.index.mapper.MapperService.checkNewMappersCompatibility(MapperService.java:363)
        at org.elasticsearch.index.mapper.MapperService.merge(MapperService.java:319)
        at org.elasticsearch.index.mapper.MapperService.merge(MapperService.java:265)
        at org.elasticsearch.cluster.metadata.MetaDataMappingService$2.execute(MetaDataMappingService.java:444)
        at org.elasticsearch.cluster.service.InternalClusterService$UpdateTask.run(InternalClusterService.java:388)
        at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:231)
        at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:194)
        ... 3 more
``` 
Config:
```
  client.mode = 'transport'
  client.hosts = [
      [host:'localhost', port:9400]
   ]
```
Domain:
```
    class A{
        ....
        static hasMany = [applicableSeries: B]
        static searchable={
            ....
            applicableSeries component: true
        }
    }

    class B{
        static belongsTo = [a:A]
        Series series
        static searchable={
            only=['series']
            series  component: 'inner'
         }
    }
```

**Comment by yang22zhang** [comment]
Other Domain has the same name but different nodes

```
class C{
static searchable={
            ....
            applicableSeries component: 'inner'
        }
}
```
