### ISSUE TITLE
Conflicting module versions

### ISSUE THREAD

**Issue by uddhaumesh** [noamt/elasticsearch-grails-plugin#172]
## Unable to deploy my application which contains grails-elasticsearch-plugin v0.1.0 and my Grails 2.4.5

``` groovy
 log4j:ERROR Error initializing log4j: null
 java.lang.ExceptionInInitializerError
    at org.codehaus.groovy.runtime.InvokerHelper.<clinit>(InvokerHelper.java:61)
    at groovy.lang.GroovyObjectSupport.<init>(GroovyObjectSupport.java:32)
    at org.codehaus.groovy.grails.commons.AbstractGrailsApplication.<init>(  
             AbstractGrailsApplication.java:45)
    at org.codehaus.groovy.grails.commons.DefaultGrailsApplication.<init>
            (DefaultGrailsApplication.java:95)
    at org.codehaus.groovy.grails.commons.DefaultGrailsApplication.<init>
            (DefaultGrailsApplication.java:91)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance( 
            NativeConstructorAccessorImpl.java:62)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(   
        DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
    at java.lang.Class.newInstance(Class.java:442)


    at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:314)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
    at java.lang.Thread.run(Thread.java:745)
 **Caused by: groovy.lang.GroovyRuntimeException: Conflicting module versions. Module [groovy-all is  loaded in version 2.3.11 and you are trying to load version 2.4.4**
```

Does Grails 2.4.5 supports elasticsearch v0.1.0.....?

**Comment by puneetbehl** [comment]
Can you create a sample application replicating this problem?

**Comment by uddhaumesh** [comment]
I am using GGTS version:3.6.1 and Grails version: 2.4.5 

below are two domain classes (i,e Student and Category)

```
class Student {
	String name
	String age
	
	Category category
	static searchable={
		name boost:2.0
		category component:true
	}
	static constraints = {
   	}
}
```

```
class Category {
	String categoryname
	static searchable = true

    static constraints = {
    }
}
```

In BuildConfig.groovy 
 ```
plugins {
	runtime ':elasticsearch:0.1.0'
    }
```
    
In Config.groovy

```
elasticSearch.client.mode = 'local';
elasticSearch.datastoreImpl = 'hibernateDatastore';
```

Later I added the below code to Config.groovy

```
def elasticsearchVersion = '2.3.3'		
ext['elasticsearch.version'] = elasticsearchVersion
```


This application is working fine in GGTS , but when I deploy it in Apache tomcat I am getting Error.

**Comment by puneetbehl** [comment]
It seems like there are multiple versions of groovy in the classpath. Looks similar to http://stackoverflow.com/questions/31099214/tomcat-conflicting-module-versions-module-groovy-all-is-loaded-in-version-2-3

**Comment by puneetbehl** [comment]
@uddhaumesh any updates on this?

**Comment by jako512** [comment]
I have the same problem with version 0.0.4.5 and Grails 2.5.5.
Workaround is to exclude `groovy-all` in `BuildConfig.groovy`:
```
grails.project.dependency.resolution = {
	plugins {
		compile ":elasticsearch:0.0.4.5", { exclude "groovy-all" } // elasticsearch 1.6.0
	}
}
```
I think that dependency on `groovy-all` should be excluded directly in plugin.

**Comment by puneetbehl** [comment]
I have created a new section called faqs in the end of documentation.
