### ISSUE TITLE
ElasticSearch fails in Grails 3.3.0.M2

### ISSUE THREAD

**Issue by bruno-lopes** [noamt/elasticsearch-grails-plugin#198]
Hi people.

I'm testing Grails 3.3.0.M2. In this version, ElasticSearch 1.2.1 fails with this problem: 

```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'searchableClassMappingConfigurator': Invocation of init method failed; nested exception is org.grails.core.exceptions.GrailsConfigurationException: The method [public abstract org.grails.datastore.mapping.model.PersistentEntity org.grails.datastore.mapping.model.MappingContext.getPersistentEntity(java.lang.String)] cannot be accessed before GORM has initialized
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1628)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:555)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483)
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:761)
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:866)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:542)
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:737)
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:370)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:314)
        at grails.boot.GrailsApp.run(GrailsApp.groovy:83)
        at grails.boot.GrailsApp.run(GrailsApp.groovy:388)
        at grails.boot.GrailsApp.run(GrailsApp.groovy:375)
        at grails.boot.GrailsApp$run.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:133)
        at sagui.api.Application.main(Application.groovy:8)
Caused by: org.grails.core.exceptions.GrailsConfigurationException: The method [public abstract org.grails.datastore.mapping.model.PersistentEntity org.grails.datastore.mapping.model.MappingContext.getPersistentEntity(java.lang.String)] cannot be accessed before GORM has initialized
        at grails.core.DefaultGrailsApplication$1.invoke(DefaultGrailsApplication.java:112)
        at com.sun.proxy.$Proxy31.getPersistentEntity(Unknown Source)
        at org.grails.core.DefaultGrailsDomainClass.verifyContextIsInitialized(DefaultGrailsDomainClass.java:162)
        at org.grails.core.DefaultGrailsDomainClass.initializePersistentProperties(DefaultGrailsDomainClass.java:101)
        at org.grails.core.DefaultGrailsDomainClass.getPersistentProperties(DefaultGrailsDomainClass.java:273)
        at grails.plugins.elasticsearch.mapping.SearchableDomainClassMapper.getDomainProperties(SearchableDomainClassMapper.groovy:311)
        at grails.plugins.elasticsearch.mapping.SearchableDomainClassMapper.buildClassMapping(SearchableDomainClassMapper.groovy:129)
        at grails.plugins.elasticsearch.mapping.SearchableClassMappingConfigurator.mappings(SearchableClassMappingConfigurator.groovy:65)
        at grails.plugins.elasticsearch.mapping.SearchableClassMappingConfigurator.configureAndInstallMappings(SearchableClassMappingConfigurator.groovy:55)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1426)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeCustomInitMethod(AbstractAutowireCapableBeanFactory.java:1758)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1695)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1624)
        ... 21 common frames omitted

```

I'm using the following configuration of ElasticSearch:
```groovy
elasticSearch.client.mode = 'local'
elasticSearch.datastoreImpl = 'hibernateDatastore'
elasticSearch.bulkIndexOnStartup = false
```

I think this may be related to this (https://github.com/longwa/build-test-data/issues/74) and this (https://github.com/longwa/build-test-data/issues/76). Anyway, ElasticSearch uses method doWithSpring to initialize. Perhaps it should use some event of GORM (emmited when it is ready) to initialize?

**Comment by bruno-lopes** [comment]
I'm using a multi-project approach. I'll try to reproduce in a simple example. I'm also using some plugins. I don't know if they are interfering.

**Comment by puneetbehl** [comment]
@bruno-lopes please share the simple project replicating the problem

**Comment by bruno-lopes** [comment]
@puneetbehl, thanks for your response. I create this simple multi-project to demonstrate the error: https://github.com/vaidegrails/ElasticSearchError/

If you need more information, please let me know.

I'm new to multi-projects in Grails 3, so, it can be my mistake. Thanks in advance.

**Comment by bruno-lopes** [comment]
@puneetbehl, could you please inspect this pr (https://github.com/noamt/elasticsearch-grails-plugin/pull/199)?
I know there must be a better way to implement, but I'm migrating our system from Grails 2 to 3 in a "fast and furious" way. :grin:

**Comment by tobisinghania** [comment]
Any updates on this?

**Comment by WAGuerra** [comment]
This problem occurs because grails see [grails domain class api is deprecated](http://docs.grails.org/latest/guide/upgrading.html#_grails_domain_class_api_deprecated).
The exception you getting says "cannot be accessed before GORM has initialized" which is exactly what is telling on Grails 3.3.x manual.
The elasticsearch plugin must be updated to work on Grails 3.3.x.
You should use grails 3.2.x instead and wait for update.

**Comment by verglor** [comment]
@puneetbehl No version of this plugin works in Grails 3.3 so I think this is a major issue that should have the highest possible priority.

**Comment by puneetbehl** [comment]
@verglor yes I totally agree with you. I am working on it. Just little slow as I need to work on my main project during the day and in evening I work on open source work. But, I will get 3.3 compatible version real soon.

**Comment by KoloritnijClap** [comment]
@puneetbehl any updates on that? Maybe you can provide at least roughly estimate, if it possible..

**Comment by jharlan-nextcentury** [comment]
@KoloritnijClap The 2.4.0.RC1 branch has 3.3 support. Still needs testing, but I'll keep an eye on the issue tracker here if anything comes up regarding the new branch.

**Comment by KoloritnijClap** [comment]
@jharlan-nextcentury I've tried it today and has class not found exception

**Comment by verglor** [comment]
Tried with [com.github.noamt:elasticsearch-grails-plugin:2.4.0.RC1-SNAPSHOT](https://jitpack.io/com/github/noamt/elasticsearch-grails-plugin/2.4.0.RC1-v1.2.1-g3c6e036-36/build.log) in Grails 3.3.0 and got `ClassNotFoundException: org.elasticsearch.common.xcontent.NamedXContentRegistry` ([full stacktrace](https://pastebin.com/aL9peNhT))

**Comment by dustindclark** [comment]
I have this working in Grails 3.3.2/GORM 6.1.8 with the following build.gradle config:

```
def esVersion = '5.4.1'
ext['elasticsearch.version'] = esVersion

ext {
    elasticsearchVersion = esVersion
}
```

```
dependencies {
...
    compile 'org.grails.plugins:elasticsearch:2.4.0.RC1'
    runtime 'org.elasticsearch.plugin:mapper-attachments:2.4.6'
...
}
```
