### ISSUE TITLE
java.lang.IllegalStateException while loading ApplicationContext duting Integration tests start up

### ISSUE THREAD

**Issue by marcos-carceles** [noamt/elasticsearch-grails-plugin#70]
Hi,

We are using grails 2.4.4 and the elastic search plugin 0.0.3.7.

When we try to run the integration tests phase `grails test-app integration: --stacktrace`, during start up, right before running any tests we get the following error:
```
| Error Fatal error running tests: Error creating bean with name 'searchableClassMappingConfigurator': Invocation of init method failed; nested exception is java.lang.IllegalStateException: Could not find ApplicationContext, configure Grails correctly first (NOTE: Stack trace has been filtered. Use --verbose to see entire trace.)
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'searchableClassMappingConfigurator': Invocation of init method failed; nested exception is java.lang.IllegalStateException: Could not find ApplicationContext, configure Grails correctly first
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1554)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:539)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:475)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:228)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:298)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:193)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:706)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:762)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:482)
	at _GrailsTest$_run_closure1.doCall(_GrailsTest.groovy:102)
	at org.codehaus.gant.GantMetaClass.invokeMethod(GantMetaClass.java:133)
	at org.codehaus.gant.GantBinding$_initializeGantBinding_closure5_closure16_closure18.doCall(GantBinding.groovy:185)
	at org.codehaus.gant.GantBinding$_initializeGantBinding_closure5_closure16_closure18.doCall(GantBinding.groovy)
	at org.codehaus.gant.GantBinding.withTargetEvent(GantBinding.groovy:90)
	at org.codehaus.gant.GantBinding.this$4$withTargetEvent(GantBinding.groovy)
	at org.codehaus.gant.GantBinding$_initializeGantBinding_closure5_closure16.doCall(GantBinding.groovy:185)
	at org.codehaus.gant.GantBinding$_initializeGantBinding_closure5_closure16.doCall(GantBinding.groovy)
	at org.codehaus.gant.GantMetaClass.invokeMethod(GantMetaClass.java:133)
	at TestApp$_run_closure1.doCall(TestApp.groovy:32)
	at org.codehaus.gant.GantMetaClass.invokeMethod(GantMetaClass.java:133)
	at org.codehaus.gant.GantBinding$_initializeGantBinding_closure5_closure16_closure18.doCall(GantBinding.groovy:185)
	at org.codehaus.gant.GantBinding$_initializeGantBinding_closure5_closure16_closure18.doCall(GantBinding.groovy)
	at org.codehaus.gant.GantBinding.withTargetEvent(GantBinding.groovy:90)
	at org.codehaus.gant.GantBinding.this$4$withTargetEvent(GantBinding.groovy)
	at org.codehaus.gant.GantBinding$_initializeGantBinding_closure5_closure16.doCall(GantBinding.groovy:185)
	at org.codehaus.gant.GantBinding$_initializeGantBinding_closure5_closure16.doCall(GantBinding.groovy)
	at gant.Gant$_dispatch_closure5.doCall(Gant.groovy:381)
	at gant.Gant$_dispatch_closure7.doCall(Gant.groovy:415)
	at gant.Gant$_dispatch_closure7.doCall(Gant.groovy)
	at gant.Gant.withBuildListeners(Gant.groovy:427)
	at gant.Gant.this$2$withBuildListeners(Gant.groovy)
	at gant.Gant$this$2$withBuildListeners$0.callCurrent(Unknown Source)
	at gant.Gant.dispatch(Gant.groovy:415)
	at gant.Gant.this$2$dispatch(Gant.groovy)
	at gant.Gant.invokeMethod(Gant.groovy)
	at gant.Gant.executeTargets(Gant.groovy:591)
	at gant.Gant.executeTargets(Gant.groovy:590)
Caused by: java.lang.IllegalStateException: Could not find ApplicationContext, configure Grails correctly first
	at grails.util.Holders.getApplicationContext(Holders.java:97)
	at org.grails.plugins.elasticsearch.mapping.ElasticSearchMappingFactory.treatValueAsAString(ElasticSearchMappingFactory.groovy:180)
	at org.grails.plugins.elasticsearch.mapping.ElasticSearchMappingFactory$_getMappingProperties_closure2.doCall(ElasticSearchMappingFactory.groovy:136)
	at org.grails.plugins.elasticsearch.mapping.ElasticSearchMappingFactory.getMappingProperties(ElasticSearchMappingFactory.groovy:67)
	at org.grails.plugins.elasticsearch.mapping.ElasticSearchMappingFactory.getElasticMapping(ElasticSearchMappingFactory.groovy:47)
	at org.grails.plugins.elasticsearch.mapping.ElasticSearchMappingFactory$_getMappingProperties_closure2.doCall(ElasticSearchMappingFactory.groovy:120)
	at org.grails.plugins.elasticsearch.mapping.ElasticSearchMappingFactory.getMappingProperties(ElasticSearchMappingFactory.groovy:67)
	at org.grails.plugins.elasticsearch.mapping.ElasticSearchMappingFactory.getElasticMapping(ElasticSearchMappingFactory.groovy:47)
	at org.grails.plugins.elasticsearch.mapping.ElasticSearchMappingFactory$getElasticMapping.call(Unknown Source)
	at org.grails.plugins.elasticsearch.mapping.SearchableClassMappingConfigurator.installMappings(SearchableClassMappingConfigurator.groovy:108)
	at org.grails.plugins.elasticsearch.mapping.SearchableClassMappingConfigurator$installMappings.callCurrent(Unknown Source)
	at org.grails.plugins.elasticsearch.mapping.SearchableClassMappingConfigurator.configureAndInstallMappings(SearchableClassMappingConfigurator.groovy:51)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeCustomInitMethod(AbstractAutowireCapableBeanFactory.java:1682)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1621)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1550)
	... 37 more
| Error Fatal error running tests: Error creating bean with name 'searchableClassMappingConfigurator': Invocation of init method failed; nested exception is java.lang.IllegalStateException: Could not find ApplicationContext, configure Grails correctly first
| Tests FAILED  - view reports in /Users/marcoscarceles/dev/projects/endource/target/test-reports
| Error Error executing script TestApp: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'searchableClassMappingConfigurator': Invocation of init method failed; nested exception is java.lang.IllegalStateException: Could not find ApplicationContext, configure Grails correctly first (NOTE: Stack trace has been filtered. Use --verbose to see entire trace.)
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'searchableClassMappingConfigurator': Invocation of init method failed; nested exception is java.lang.IllegalStateException: Could not find ApplicationContext, configure Grails correctly first
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1554)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:539)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:475)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:228)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:298)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:193)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:706)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:762)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:482)
	at _GrailsTest$_run_closure1.doCall(_GrailsTest.groovy:102)
	at org.codehaus.gant.GantMetaClass.invokeMethod(GantMetaClass.java:133)
	at org.codehaus.gant.GantBinding$_initializeGantBinding_closure5_closure16_closure18.doCall(GantBinding.groovy:185)
	at org.codehaus.gant.GantBinding$_initializeGantBinding_closure5_closure16_closure18.doCall(GantBinding.groovy)
	at org.codehaus.gant.GantBinding.withTargetEvent(GantBinding.groovy:90)
	at org.codehaus.gant.GantBinding.this$4$withTargetEvent(GantBinding.groovy)
	at org.codehaus.gant.GantBinding$_initializeGantBinding_closure5_closure16.doCall(GantBinding.groovy:185)
	at org.codehaus.gant.GantBinding$_initializeGantBinding_closure5_closure16.doCall(GantBinding.groovy)
	at org.codehaus.gant.GantMetaClass.invokeMethod(GantMetaClass.java:133)
	at TestApp$_run_closure1.doCall(TestApp.groovy:32)
	at org.codehaus.gant.GantMetaClass.invokeMethod(GantMetaClass.java:133)
	at org.codehaus.gant.GantBinding$_initializeGantBinding_closure5_closure16_closure18.doCall(GantBinding.groovy:185)
	at org.codehaus.gant.GantBinding$_initializeGantBinding_closure5_closure16_closure18.doCall(GantBinding.groovy)
	at org.codehaus.gant.GantBinding.withTargetEvent(GantBinding.groovy:90)
	at org.codehaus.gant.GantBinding.this$4$withTargetEvent(GantBinding.groovy)
	at org.codehaus.gant.GantBinding$_initializeGantBinding_closure5_closure16.doCall(GantBinding.groovy:185)
	at org.codehaus.gant.GantBinding$_initializeGantBinding_closure5_closure16.doCall(GantBinding.groovy)
	at gant.Gant$_dispatch_closure5.doCall(Gant.groovy:381)
	at gant.Gant$_dispatch_closure7.doCall(Gant.groovy:415)
	at gant.Gant$_dispatch_closure7.doCall(Gant.groovy)
	at gant.Gant.withBuildListeners(Gant.groovy:427)
	at gant.Gant.this$2$withBuildListeners(Gant.groovy)
	at gant.Gant$this$2$withBuildListeners$0.callCurrent(Unknown Source)
	at gant.Gant.dispatch(Gant.groovy:415)
	at gant.Gant.this$2$dispatch(Gant.groovy)
	at gant.Gant.invokeMethod(Gant.groovy)
	at gant.Gant.executeTargets(Gant.groovy:591)
	at gant.Gant.executeTargets(Gant.groovy:590)
Caused by: java.lang.IllegalStateException: Could not find ApplicationContext, configure Grails correctly first
	at grails.util.Holders.getApplicationContext(Holders.java:97)
	at org.grails.plugins.elasticsearch.mapping.ElasticSearchMappingFactory.treatValueAsAString(ElasticSearchMappingFactory.groovy:180)
	at org.grails.plugins.elasticsearch.mapping.ElasticSearchMappingFactory$_getMappingProperties_closure2.doCall(ElasticSearchMappingFactory.groovy:136)
	at org.grails.plugins.elasticsearch.mapping.ElasticSearchMappingFactory.getMappingProperties(ElasticSearchMappingFactory.groovy:67)
	at org.grails.plugins.elasticsearch.mapping.ElasticSearchMappingFactory.getElasticMapping(ElasticSearchMappingFactory.groovy:47)
	at org.grails.plugins.elasticsearch.mapping.ElasticSearchMappingFactory$_getMappingProperties_closure2.doCall(ElasticSearchMappingFactory.groovy:120)
	at org.grails.plugins.elasticsearch.mapping.ElasticSearchMappingFactory.getMappingProperties(ElasticSearchMappingFactory.groovy:67)
	at org.grails.plugins.elasticsearch.mapping.ElasticSearchMappingFactory.getElasticMapping(ElasticSearchMappingFactory.groovy:47)
	at org.grails.plugins.elasticsearch.mapping.ElasticSearchMappingFactory$getElasticMapping.call(Unknown Source)
	at org.grails.plugins.elasticsearch.mapping.SearchableClassMappingConfigurator.installMappings(SearchableClassMappingConfigurator.groovy:108)
	at org.grails.plugins.elasticsearch.mapping.SearchableClassMappingConfigurator$installMappings.callCurrent(Unknown Source)
	at org.grails.plugins.elasticsearch.mapping.SearchableClassMappingConfigurator.configureAndInstallMappings(SearchableClassMappingConfigurator.groovy:51)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeCustomInitMethod(AbstractAutowireCapableBeanFactory.java:1682)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1621)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1550)
	... 37 more
| Error Error executing script TestApp: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'searchableClassMappingConfigurator': Invocation of init method failed; nested exception is java.lang.IllegalStateException: Could not find ApplicationContext, configure Grails correctly first
```

The error seems to be trying to get access to the applicationContext here:
https://github.com/noamt/elasticsearch-grails-plugin/blob/master/src/groovy/org/grails/plugins/elasticsearch/mapping/ElasticSearchMappingFactory.groovy#L180

This error seems to occur only during integration tests, and not when running the application `grails run-app`

**Comment by marcos-carceles** [comment]
Closed by PR #71
